Gzip js
o-d-i-n/HelloWorld pull request #24
Opened 2017-08-21 15:49 UTC by ayushgarg1804

Wrapping up Gzipping Javascript resources and configuring production environment in webpack. Also includes middleware for minifying HTML.

2017-08-22 06:10 UTC, mbad0la requested changes
Just a small change. Everything else looks good

2017-08-22 06:10 UTC, mbad0la commented on helloWorld/settings.py
> +    'htmlmin.middleware.HtmlMinifyMiddleware',
This is not required

2017-08-23 09:04 UTC, ayushgarg1804 commented on helloWorld/settings.py
> +    'htmlmin.middleware.HtmlMinifyMiddleware',
Why is it not required? I know html size is quite low for now but I included it for making it scalable.

2017-08-24 02:24 UTC, mbad0la commented on helloWorld/settings.py
> +    'htmlmin.middleware.HtmlMinifyMiddleware',
As this is a React-mounted application and we aren't intending to implement server-side rendering, the HTML content we have atm is final. Hence, there isn't any need to scale.

But anyway, there is no impact of this plugin, so I'll merge this!

2017-08-24 02:25 UTC, merged